### ISSUE TITLE
Training code keeps running for PyTorch after training is done

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench-core#26]
There is some issue where after a goal is reached, the python process running the training doesn't exit, with
```
Exception ignored in: <bound method tqdm.__del__ 
Traceback (most recent call last):
  File "/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/conda/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/conda/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```
This seems to be due to https://github.com/tqdm/tqdm/issues/613 though it's hard to tell what the cause is. It might be due to the torchvision dataloader progessbar, as that's the only place I found that uses tqdm, but the progressbar is only relevant at the statr of training, so it should no influence the end of training.

This doesn't influence training in any way, it just means the current run has to be manually deleted before a new run can be started, as the current run is stuck in the "running" state due to this.

**Comment by ehoelzl** [comment]
Is this still the case ?

**Comment by Panaetius** [comment]
I wouldn't know, been a while since I last ran it

**Comment by ehoelzl** [comment]
Closing as this is not an issue anymore
