### ISSUE TITLE
Downloading results fails if `--output` option is not provided

### ISSUE THREAD

**Issue by cgrigis** [mlbench/mlbench-core#57]
Downloading results fails when `-o` is not provided (as shown in https://mlbench.github.io/2019/11/11/mlbench-cli/):
```
$ mlbench download my-run-1 
WARNING:root:No ExternalIP found for NodePort Service. Trying InternalIP. This only works if the cluster internal IP's are reachable.
Traceback (most recent call last):
  File "/home/cgrigis/.virtualenvs/mlbench/bin/mlbench", line 8, in <module>
    sys.exit(cli())
  File "/home/cgrigis/.virtualenvs/mlbench/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cgrigis/.virtualenvs/mlbench/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cgrigis/.virtualenvs/mlbench/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cgrigis/.virtualenvs/mlbench/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cgrigis/.virtualenvs/mlbench/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cgrigis/.virtualenvs/mlbench/lib/python3.7/site-packages/mlbench_core/cli/cli.py", line 286, in download
    with open(output, "wb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Looking at the code, the option should either be marked `required` or provide a `default`.

**Comment by martinjaggi** [comment]
thanks a lot!
