### ISSUE TITLE
RefreshError from gcloud

### ISSUE THREAD

**Issue by giorgiosav** [mlbench/mlbench-core#83]
This sometimes happens to me - right now I am running locally from my laptop with GCloud credentials, but I believe it has also happened when running directly from cloud.google.com. Despite the error, the cluster gets created anyway.

```
giorgio -> mlbench create-cluster gcloud -g 1 --gpu-type nvidia-tesla-k80 2 giorgio

Wait for firewall to be available for deletion
Traceback (most recent call last):
  File "/Users/giorgio/anaconda3/bin/mlbench", line 8, in <module>
    sys.exit(cli())
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/mlbench_core/cli/cli.py", line 467, in create_gcloud
    credentials.refresh(auth_req)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 111, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/Users/giorgio/anaconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 61, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Invalid OAuth scope or ID token audience provided.', '{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}')
```

**Comment by ehoelzl** [comment]
This is due to unstable connections (most probably)
