### ISSUE TITLE
Cluster creation/deletion errors with non-default zone

### ISSUE THREAD

**Issue by giorgiosav** [mlbench/mlbench-core#94]
Yesterday I created a cluster like this
`mlbench create-cluster gcloud -g 1 --gpu-type nvidia-tesla-t4 -z europe-west2-b 3 giorgio`

After some work, I deleted the cluster with the Google Cloud GUI ("remove instance group"). 

This morning I logged in and, as expected, did not have any active clusters in the "Resources" widget of Google Cloud. I created a cluster with the same command as above and got this error:

```
2020-05-18 11:29:37.243505: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.
so.6: cannot open shared object file: No such file or directory
2020-05-18 11:29:37.243857: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libn
vinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-05-18 11:29:37.243884: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU wit
h TensorRT, please make sure the missing libraries mentioned above are installed properly.
Wait for firewall to be available for deletion
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.ALREADY_EXISTS
        details = "Already exists: projects/mlbench-giorgio/zones/europe-west2-b/clusters/giorgio-3."
        debug_error_string = "{"created":"@1589794188.706528633","description":"Error received from peer ipv4:64.233.184.95:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Already exists: projects/mlbench-giorgio/zones/europe-west2-b/clusters/giorgio-3.","grpc_status":6}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/giorgiosaza/.local/bin/mlbench", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/giorgiosaza/.local/lib/python3.7/site-packages/mlbench_core/cli/cli.py", line 418, in create_gcloud
    response = gclient.create_cluster(None, None, cluster, parent=name_path)
  File "/home/giorgiosaza/.local/lib/python3.7/site-packages/google/cloud/container_v1/gapic/cluster_manager_client.py", line 467, in create_cluster
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.AlreadyExists: 409 Already exists: projects/mlbench-giorgio/zones/europe-west2-b/clusters/giorgio-3.
```

So then I tried to delete the cluster (which didn't show up under "Resources", so it didn't actually exist) and got this error:
`mlbench delete-cluster gcloud giorgio-3`
```
2020-05-18 11:41:29.472136: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.
so.6: cannot open shared object file: No such file or directory
2020-05-18 11:41:29.472261: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libn
vinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-05-18 11:41:29.472276: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU wit
h TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Not found: projects/mlbench-giorgio/zones/europe-west1-b/clusters/giorgio-3."
        debug_error_string = "{"created":"@1589794890.436286432","description":"Error received from peer ipv4:173.194.76.95:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Not found: projects/mlbench-giorgio/zones/europe-west1-b/clusters/giorgio-3.","grpc_status":5}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/giorgiosaza/.local/bin/mlbench", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/giorgiosaza/.local/lib/python3.7/site-packages/mlbench_core/cli/cli.py", line 306, in delete_gcloud
    response = gclient.delete_cluster(None, None, None, name=cluster_path)
  File "/home/giorgiosaza/.local/lib/python3.7/site-packages/google/cloud/container_v1/gapic/cluster_manager_client.py", line 1543, in delete_cluster
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.NotFound: 404 Not found: projects/mlbench-giorgio/zones/europe-west1-b/clusters/giorgio-3.
```

I think the root cause of this problem is that I created the cluster in zone `europe-west2-b`, when my default zone is `europe-west1-b`: in fact when I executed `mlbench delete-cluster gcloud -z europe-west2-b giorgio-3` it worked fine. But there are a couple of questions still:

* Why did the first error come up, when re-creating the cluster after I deleted it with the Gcloud GUI?
* Should we check all zones with `mlbench delete-cluster`? If not, I think we should print a message saying something like "cluster not found: are you sure you entered the correct zone?".

**Comment by giorgiosav** [comment]
This seems to be a problem with the Gcloud dashboard, which for some reason doesn't actually delete clusters created with the command line. We should add a note about this on the tutorials. In the meantime I added some exception handling in PR #102 so users know how to handle this.
